### ISSUE TITLE
Crash on server startup

### ISSUE THREAD

**Issue by Neubulae** [JamiesWhiteShirt/reach-entity-attributes#2]
https://pastebin.com/a5H64e4U

**Comment by JamiesWhiteShirt** [comment]
Please share a more complete log - I can't see which version of Minecraft nor which other mods (except worldedit) you have installed so I can try reproducing it.

**Comment by Neubulae** [comment]
[crash-2020-04-11_02.15.03-server.txt](https://github.com/JamiesWhiteShirt/reach-entity-attributes/files/4463116/crash-2020-04-11_02.15.03-server.txt)

**Comment by Neubulae** [comment]
as the other issue suggest, Carpet could be a problem. But I also installed AttributeFix which modifies attribute so… maybe both?

**Comment by Tigereye504** [comment]
This issue has come up once more, In both cases the key failure seems to occur within ServerPlayerInteractionManagerMixin::modifyReachDistance. Was this fixed in any of the 1.16 versions? If so, then I'll problably just need to get Hemea to update to the appropriate version as it is using 1.0.1 as a dependency.

https://github.com/Tigereye504/chestcavity/issues/15
